### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by judithrocketmakers** [mmdevries/eiows#10]
While I can hack together a quick Typescript definitions file for eiows, it would be really helpful to have an official types package for the sake of imports handling, either as part of this package or as @types/eiows. Apologies if there is one and I just failed to find it!

**Comment by mmdevries** [comment]
Besides CommonJS module also ESM module system is supported. You should be able to do something like this:
import { eiows } from 'eiows';

This is added to version 6.6.0
