### ISSUE TITLE
eiows deprecated ?

### ISSUE THREAD

**Issue by apydo** [mmdevries/eiows#14]
Hello,

I can see deprecation warning for eiows in npm.
@mmdevries, could you please explain your plans for maintaining eiows... or not ? Thanks.

**Comment by AskAlice** [comment]
@mmdevries please update us on this.

Also I noticed your git config is wrong. Your git config email address should match your github email, or you should use the no-reply email associated with your username. see [Github Docs: Setting your commit email address on GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github)

```bash
git config --global user.email mmdevries@users.noreply.github.com
```

this should ensure that your commits get the proper attribution and your commits show up in your contribution graph on your profile

**Comment by mmdevries** [comment]
windows support will be dropped.
