### ISSUE TITLE
Can we use it in typescript with types declaration?

### ISSUE THREAD

**Issue by mistryaksh** [mmdevries/eiows#18]
'wsServer' is declared but its value is never read.ts(6133)
Could not find a declaration file for module 'eiows'. '/Users/aakashmistry/Desktop/2023-projects/freelancer/apna-mentor/backend/node_modules/eiows/dist/eiows.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/eiows` if it exists or add a new declaration (.d.ts) file containing `declare module 'eiows';`ts(7016)

Types installation was not found  using dev types command

**Comment by mmdevries** [comment]
The eiows.d.ts has been added in version 6.7.0.
Please let me know if this solves your issue.
