### ISSUE TITLE
Nodejs 20.12.0 issue

### ISSUE THREAD

**Issue by thenitai** [mmdevries/eiows#20]
Had it installed with the latest node 20.11.x but as of today the app doesn't start anymore as the module cannot be compiled anymore under 20.12.0.

**Comment by mmdevries** [comment]
Are you sure you recompiled the module for node 20.12.0? Can you send me the build_log.txt file then I will take a look. In my environment I don't see any build issues for node 20.12.0.

**Comment by thenitai** [comment]
> Are you sure you recompiled the module for node 20.12.0? Can you send me the build_log.txt file then I will take a look. In my environment I don't see any build issues for node 20.12.0.

When I have 20.12.0 installed and include eiows I get this error message:
```
Compilation of µWebSockets has failed.Please install a supported C++17 compiler, git and/or update node and reinstall the module 'eiows'.
```
Going back to 20.11.x works.
In both cases, I remove the whole node_modules folder, and reinstall everything. This happens in macOS and Ubuntu 22.04.

**Comment by mmdevries** [comment]
On the mac indeed the build failed. I have change the clang option on macOS and now it should work with eiows version 7.0.1. On ubuntu I don't see any build issues. Are you sure you are using gcc? And if so, which version are you using?

**Comment by thenitai** [comment]
Just tried it on Ubuntu again. Same message.

```
g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

**Comment by mmdevries** [comment]
Strange I use the same version without any issues. It would be really
helpful if you could send me the build_log.txt file which is stored in the
node_modules/eiows folder.

Op vr 29 mrt 2024 om 10:48 schreef Nitai ***@***.***>:

**Comment by thenitai** [comment]
This is resolved with the latest release
