### ISSUE TITLE
Use eiows as an optional dependency

### ISSUE THREAD

**Issue by brako** [mmdevries/eiows#22]
Hello,

I am trying to use eiows as an optional dependency on my project. My project is running on Windows and Linux.
So I want to use eiows on Linux and switch to native ws on Windows.

But I can't use eiows as an optional dependency, because npm does not know the supported os for the module and will try to install it on Windows anyway.

Is it possible to add explicitly the supported os to the package.json file ?

For example:

```
{
  "os": ["!win32", "linux", "freebsd", "darwin"]
}
```
[NPM documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os)

Thanks!

**Comment by mmdevries** [comment]
This should now be defined in the 7.1.0 version.

**Comment by brako** [comment]
I have tested and it is working! thanks
