### ISSUE TITLE
Version 3.3.1 seems to fail on Node.js 14

### ISSUE THREAD

**Issue by darrachequesne** [mmdevries/eiows#4]
Hi Matthijs, hope you are fine!

We are relying on `eiows` in our Engine.IO tests, and the last CI build has failed: https://travis-ci.org/github/socketio/engine.io/jobs/731765178

The error message:

> Error: Cannot find module './eiows_linux_83'

Could it be related to https://github.com/mmdevries/eiows/commit/0f048e33ad5b70ed53c913355e8bb4956469c288?

Edit: https://travis-ci.org/github/socketio/engine.io/jobs/731765178 (fail) uses `v14.13.0`, while https://travis-ci.org/github/socketio/engine.io/jobs/729786011 (success) uses `v14.12.0`, so that may be linked to the minor version bump.

**Comment by mmdevries** [comment]
Hi Damien,

Yes, I am fine thank you.
Unfortunately there are some dependencies to the internals of nodejs to receive the SSL context.
I have added the new headers for node 14.13.0 and now it should work again.
It's solved on eiows version 3.3.2.

**Comment by darrachequesne** [comment]
Like, already? Awesome, thanks!
