### ISSUE TITLE
Misrepresenting

### ISSUE THREAD

**Issue by ghost** [mmdevries/eiows#5]
I found this via the Socket.IO website. If you want to fork open source you better read the actual license:

> 2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.

I don't see any marks of these sources being modified and the LICENSE does not state what changes have been made, it still lists only me - which is incorrect. This is 33% of the conditions.

**Comment by mmdevries** [comment]
Sorry for my ignorance.
I have updated the LICENSE files.
