### ISSUE TITLE
Example posted does not work

### ISSUE THREAD

**Issue by d3x0r** [mmdevries/eiows#7]
Socket.IO expects wsEngine to be a constructor, not a string so...

```
var io = require("socket.io")(server, {
    wsEngine: 'eiows',
    perMessageDeflate: {
        threshold: 32768
    }
});
```

fails but I managed to get it to work with 

```
var io = require("socket.io")(server, {
    wsEngine: require("eiows").Server,
});
```

**Comment by mmdevries** [comment]
Thanks for the remark.
You are right engine.io made some breaking changes on version 5.0.0.
The example has been update.
